# Generated by Django 6.0.5 on 2026-05-20 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Образование')),
                ('name_ukr', models.CharField(max_length=255, verbose_name='Образование укр')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Срок опыта работы')),
                ('name_ukr', models.CharField(max_length=255, verbose_name='Срок опыта работы укр')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Спецификация (категория)')),
                ('name_ukr', models.CharField(max_length=255, verbose_name='Спецификация (категория) на укр')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='TypeOfEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип занятости')),
                ('name_ukr', models.CharField(max_length=255, verbose_name='Тип занятости укр')),
            ],
            options={
                'verbose_name': 'Тип занятости',
                'verbose_name_plural': 'Тип занятости',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название работы')),
                ('ukr_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название работы на укр')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.education', verbose_name='Образование')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.experience', verbose_name='Опыт работы')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.specification', verbose_name='Спецификация')),
                ('type_of_employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.typeofemployment', verbose_name='Тип занятости')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
