# Generated by Django 6.0.5 on 2026-05-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='advantages/', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='Название приемущества')),
                ('description', models.CharField(max_length=255, verbose_name='Описание преимущиства')),
                ('dop_text', models.CharField(max_length=255, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Important',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пункта')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пункта')),
            ],
        ),
        migrations.CreateModel(
            name='WillDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пункта')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='job',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, to='job.advantages', verbose_name='Преимущества'),
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название работы для описания')),
                ('important', models.ManyToManyField(blank=True, null=True, to='job.important', verbose_name='Что мы предлагаем')),
                ('offer', models.ManyToManyField(blank=True, null=True, to='job.offer', verbose_name='Что мы предлагаем')),
                ('will_do', models.ManyToManyField(blank=True, null=True, to='job.willdo', verbose_name='Что мы предлагаем')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobdescription', verbose_name='Описание для работы'),
        ),
    ]
