# Generated by Django 6.0.5 on 2026-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_advantages_important_offer_willdo_job_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание преимущиства'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='dop_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='advantages/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название приемущества'),
        ),
    ]
