# Generated by Django 6.0.5 on 2026-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_advantages_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltersJobMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направлени')),
                ('image', models.ImageField(upload_to='job-filters-main-page/', verbose_name='Фото дл направления')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на каталог')),
            ],
            options={
                'verbose_name': 'Ссылка на каталог',
                'verbose_name_plural': 'Ссылки на каталог',
            },
        ),
    ]
