# Generated by Django 6.0.5 on 2026-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_faqparagraph_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtersjobmainpage',
            name='ukr_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нарвание на UA'),
        ),
    ]
