# Generated by Django 6.0.5 on 2026-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_advantages_ukr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='ukr_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание преимущиства на UA'),
        ),
    ]
