# Generated by Django 6.0.5 on 2026-07-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_advantages_ukr_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='important',
            name='ukr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта на UA'),
        ),
        migrations.AddField(
            model_name='offer',
            name='ukr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта на UA'),
        ),
        migrations.AddField(
            model_name='willdo',
            name='ukr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта на UA'),
        ),
    ]
