# Generated by Django 6.0.5 on 2026-07-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_important_ukr_text_offer_ukr_text_willdo_ukr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='ukr_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос на UA'),
        ),
        migrations.AddField(
            model_name='faqparagraph',
            name='ukr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст параграфа на UA'),
        ),
    ]
