# Generated by Django 6.0.5 on 2026-07-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_faq_ukr_name_faqparagraph_ukr_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя менеджера')),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TownWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Город работы')),
                ('ukr_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Город работы на UA')),
            ],
            options={
                'verbose_name': 'Город работы',
                'verbose_name_plural': 'Города работы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('photo', models.ImageField(upload_to='work_applications/%Y/%m/%d/', verbose_name='Фото')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Желаемая зарплата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('telegram_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправленно'), ('error', 'Ошибка отправки')], default='pending', max_length=20, verbose_name='Статус Telegram')),
                ('telegram_error', models.TextField(blank=True, verbose_name='Ошибка Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='job.telegrammanager', verbose_name='Менеджер')),
                ('town_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='job.townwork', verbose_name='Город работы')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
