# Generated by Django 6.0.5 on 2026-07-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_telegrammanager_townwork_workapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammanager',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя (можно с инициалами)'),
        ),
    ]
