# Generated by Django 6.0.5 on 2026-07-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_telegrammanager_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workapplication',
            name='age',
        ),
        migrations.RemoveField(
            model_name='workapplication',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='workapplication',
            name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='workapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workapplication',
            name='photo',
        ),
        migrations.AddField(
            model_name='workapplication',
            name='actual_address',
            field=models.TextField(blank=True, default='', verbose_name='Фактическое место проживания'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='consent_personal_data',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='desired_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='job.job', verbose_name='Желаемая должность'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='passport_main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/passport/main/%Y/%m/%d/', verbose_name='Основной разворот паспорта или ID-карта'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия и номер паспорта или номер ID-карты'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='applications/payment_receipts/%Y/%m/%d/', verbose_name='Фото оплаты или чек'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='registered_address',
            field=models.TextField(blank=True, null=True, verbose_name='Прописка'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='registration_document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/passport/registration/%Y/%m/%d/', verbose_name='Фото прописки или документа о регистрации'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='salary_details',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты для зарплаты'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='source_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда о нас узнали'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='tax_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='РНОКПП'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ник в телеграме'),
        ),
        migrations.AlterField(
            model_name='workapplication',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='job.telegrammanager', verbose_name='Прикреплённый менеджер'),
        ),
        migrations.AlterField(
            model_name='workapplication',
            name='telegram_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправленно'), ('error', 'Ошибка отправки')], default='pending', max_length=20, verbose_name='Статус отправки в Telegram'),
        ),
    ]
