# Generated by Django 6.0.5 on 2026-07-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_workapplication_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workapplication',
            old_name='telegram',
            new_name='telegram_nickname',
        ),
    ]
